### Buscar todo os registro
GET http://localhost:3333/user

### Test Conexão
GET http://localhost:3333/user/a0931d40-e760-4de5-9659-f3480defa4e1

### Test Conexão
GET http://localhost:3333/user/b

### Test POST
POST http://localhost:3333/user/
content-type: application/json

{
    "curso": "Tecnico em Informatica",
    "uc":"Programação WEB 3",
    "name": "Rafael",
    "email":"bruno@fema.com"
}

### DELETE
DELETE http://localhost:3333/user/6e48fd43-debc-40ef-bd34-4310505afa27

### UPDATE
PUT http://localhost:3333/user/08c72358-9a48-427c-a549-02d0fbeaad76
content-type: application/json

{
    "name": "Corin",
    "email":"cora@fema.com"
}
